version: "3.9"
services:

  api:
    image: python:3.11.6-alpine3.18
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: servertree-server-api-v1
    ports:
      - "4003:4003"
    volumes:
      - .:/app
    working_dir: /app
    command:
      - /bin/sh
      - -c
      - |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install
        poetry run alembic upgrade head
        poetry run uvicorn st_server.server.interface.api.main:app --host 0.0.0.0 --port 4003 --reload
    depends_on:
      - mysql
      - rabbitmq
    links:
      - mysql
