# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: authorization.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x13\x61uthorization.proto\x12\rauthorization"?\n\x0c\x43heckRequest\x12\x0f\n\x07subject\x18\x01 \x01(\t\x12\x0e\n\x06\x61\x63tion\x18\x02 \x01(\t\x12\x0e\n\x06object\x18\x03 \x01(\t" \n\rCheckResponse\x12\x0f\n\x07\x61llowed\x18\x01 \x01(\x08\x32\x66\n\x14\x41uthorizationService\x12N\n\x0f\x43heckPermission\x12\x1b.authorization.CheckRequest\x1a\x1c.authorization.CheckResponse"\x00\x62\x06proto3'  # noqa: E501
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(
    DESCRIPTOR, "authorization_pb2", _globals
)
if _descriptor._USE_C_DESCRIPTORS is False:
    DESCRIPTOR._options = None
    _globals["_CHECKREQUEST"]._serialized_start = 38
    _globals["_CHECKREQUEST"]._serialized_end = 101
    _globals["_CHECKRESPONSE"]._serialized_start = 103
    _globals["_CHECKRESPONSE"]._serialized_end = 135
    _globals["_AUTHORIZATIONSERVICE"]._serialized_start = 137
    _globals["_AUTHORIZATIONSERVICE"]._serialized_end = 239
# @@protoc_insertion_point(module_scope)
