"""Initial.

Revision ID: 96c8eb43c22e
Revises: 
Create Date: 2023-08-21 22:35:39.959993

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "96c8eb43c22e"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "application",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("version", sa.String(length=255), nullable=False),
        sa.Column("architect", sa.String(length=255), nullable=False),
        sa.Column("discarded", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "server",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("cpu", sa.String(length=255), nullable=True),
        sa.Column("ram", sa.String(length=255), nullable=True),
        sa.Column("hdd", sa.String(length=255), nullable=True),
        sa.Column("environment", sa.String(length=255), nullable=False),
        sa.Column("operating_system", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=255), nullable=True),
        sa.Column("discarded", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "credential",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("server_id", sa.String(length=32), nullable=False),
        sa.Column("connection_type", sa.String(length=255), nullable=False),
        sa.Column("local_ip", sa.String(length=255), nullable=True),
        sa.Column("local_port", sa.String(length=255), nullable=True),
        sa.Column("public_ip", sa.String(length=255), nullable=True),
        sa.Column("public_port", sa.String(length=255), nullable=True),
        sa.Column("username", sa.String(length=255), nullable=False),
        sa.Column("password", sa.String(length=255), nullable=False),
        sa.Column("discarded", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["server_id"],
            ["server.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "server_application",
        sa.Column("server_id", sa.String(length=32), nullable=False),
        sa.Column("application_id", sa.String(length=32), nullable=False),
        sa.Column("install_dir", sa.String(length=255), nullable=True),
        sa.Column("log_dir", sa.String(length=255), nullable=True),
        sa.ForeignKeyConstraint(
            ["application_id"],
            ["application.id"],
        ),
        sa.ForeignKeyConstraint(
            ["server_id"],
            ["server.id"],
        ),
        sa.PrimaryKeyConstraint("server_id", "application_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("server_application")
    op.drop_table("credential")
    op.drop_table("server")
    op.drop_table("application")
    # ### end Alembic commands ###
