"""Initial.

Revision ID: a483a5bf4b1e
Revises: 96c8eb43c22e
Create Date: 2023-08-26 01:41:54.664929

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a483a5bf4b1e'
down_revision = '96c8eb43c22e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
