"""Server status.

Revision ID: ad0783532d3f
Revises: 2d155ce137cc
Create Date: 2023-06-25 01:49:57.975829

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "ad0783532d3f"
down_revision = "2d155ce137cc"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "server", sa.Column("status", sa.String(length=255), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("server", "status")
    # ### end Alembic commands ###
